mysql:
  image: mysql:5.6
  container_name: anvil_mysql
  ports:
    - "3306:3306"
  volumes:
    - model:/var/database_data
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=anvil
    - MYSQL_USER=webapp
    - MYSQL_PASSWORD=monkeybusiness