const ActionTypes = {
  REDIRECT_TO_ARTIST_SEARCH: "REDIRECT_TO_ARTIST_SEARCH",
  SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
  INIT_ARTIST_SEARCH: "INIT_ARTIST_SEARCH",
  FINISH_ARTIST_SEARCH: "FINISH_ARTIST_SEARCH",
  INIT_ARTIST_PAGE_LOAD: "INIT_ARTIST_PAGE_LOAD",
  FINISH_ARTIST_PAGE_LOAD: "FINISH_ARTIST_PAGE_LOAD",
  LOAD_SIMILAR_ARTISTS: "LOAD_SIMILAR_ARTISTS"
}

export default ActionTypes
