const ActionTypes = {
  SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
  INIT_ARTIST_SEARCH: "INIT_ARTIST_SEARCH",
  FINISH_ARTIST_SEARCH: "FINISH_ARTIST_SEARCH",
  INIT_ARTIST_PAGE_LOAD: "INIT_ARTIST_PAGE_LOAD",
  FINISH_ARTIST_PAGE_LOAD: "FINISH_ARTIST_PAGE_LOAD"
}

export default ActionTypes
